# -*- coding: utf-8 -*-
"""Parameters.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NTayL40SnRFmW056cinPtZmWd1lgeBrq

this file contains parameters to vary in the experiment
"""

# Watermaze
XO = 0.0                          
YO = 0.0                          

R_WATERMAZE = 1.0                  
R_PLATFORM = 0.05                

# Place cells
CELL_COUNT = 493                    
PLACE_CELL_STD = 0.16                   

# Critic and Actor
TDECAY = 0.95                   
C_LEARNING_RATE = 0.1              
A_LEARNING_RATE = 0.2               

# Simulated rat
SPEED = 0.8                     
ACTION_MOMENTUM_RATIO = 1/3     

STEP_TIME = 0.1                 
TRIAL_TIME = 120           

# Figures
SAVED_FIGURES_PATH = "./results/"